// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYz0eXIaqV9Duc0-XwA_1IPjpmG7LF30',
    appId: '1:1082814416841:web:a283545c5581953b748a18',
    messagingSenderId: '1082814416841',
    projectId: 'test-firebase-e9ca6',
    authDomain: 'test-firebase-e9ca6.firebaseapp.com',
    storageBucket: 'test-firebase-e9ca6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3ux8dgzxEQlPwlyzO4TdJNWVJcm0PJ0',
    appId: '1:1082814416841:android:0813e30387b45e9f748a18',
    messagingSenderId: '1082814416841',
    projectId: 'test-firebase-e9ca6',
    storageBucket: 'test-firebase-e9ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZhyfmxpAzxbQVu3kSlTvKp4r_6F-cYAA',
    appId: '1:1082814416841:ios:0cc52314aee6355e748a18',
    messagingSenderId: '1082814416841',
    projectId: 'test-firebase-e9ca6',
    storageBucket: 'test-firebase-e9ca6.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZhyfmxpAzxbQVu3kSlTvKp4r_6F-cYAA',
    appId: '1:1082814416841:ios:0cc52314aee6355e748a18',
    messagingSenderId: '1082814416841',
    projectId: 'test-firebase-e9ca6',
    storageBucket: 'test-firebase-e9ca6.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEYz0eXIaqV9Duc0-XwA_1IPjpmG7LF30',
    appId: '1:1082814416841:web:59d47ebd29c08225748a18',
    messagingSenderId: '1082814416841',
    projectId: 'test-firebase-e9ca6',
    authDomain: 'test-firebase-e9ca6.firebaseapp.com',
    storageBucket: 'test-firebase-e9ca6.appspot.com',
  );
}
